### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by steve98654** [bloomberg/bqplot#26]
I am running Ubuntu 14.04 and tried to both pip install and build bqplot from source following the instructions in the README file but am receiving the following error message (both dependencies ipywidgets==4.0.3 and numpy==1.9.3 are installed):

What is causing these errors; am I missing some JS dependencies?  

Thanks for the help, 
Steve Taylor 
```bash
steve98654@Riemann:~/LocRepos$ pip install bqplot
Collecting bqplot
  Using cached bqplot-0.3.8.tar.gz
Requirement already satisfied (use --upgrade to upgrade): ipywidgets in /home/steve98654/anaconda/lib/python2.7/site-packages (from bqplot)
Requirement already satisfied (use --upgrade to upgrade): numpy in /home/steve98654/anaconda/lib/python2.7/site-packages (from bqplot)
Requirement already satisfied (use --upgrade to upgrade): pandas in /home/steve98654/anaconda/lib/python2.7/site-packages (from bqplot)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /home/steve98654/anaconda/lib/python2.7/site-packages (from pandas->bqplot)
Requirement already satisfied (use --upgrade to upgrade): pytz>=2011k in /home/steve98654/anaconda/lib/python2.7/site-packages (from pandas->bqplot)
Building wheels for collected packages: bqplot
  Running setup.py bdist_wheel for bqplot
  Complete output from command /home/steve98654/anaconda/bin/python -c "import setuptools;__file__='/tmp/pip-build-Vfqxcs/bqplot/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmptfN2aypip-wheel-:
  /home/steve98654/anaconda/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'License'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  running js
  
  Error: Unknown encoding
      at Buffer.write (buffer.js:382:13)
      at new Buffer (buffer.js:261:26)
      at Object.fs.writeFileSync (fs.js:758:12)
      at Function.writeFileSync [as sync] (/usr/local/lib/node_modules/bower/node_modules/insight/node_modules/configstore/node_modules/write-file-atomic/index.js:37:12)
      at Object.create.all.set (/usr/local/lib/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:55:21)
      at Object.Configstore (/usr/local/lib/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:20:11)
      at new Insight (/usr/local/lib/node_modules/bower/node_modules/insight/lib/index.js:37:34)
      at ensureInsight (/usr/local/lib/node_modules/bower/lib/util/analytics.js:25:19)
      at Object.setup (/usr/local/lib/node_modules/bower/lib/util/analytics.js:41:9)
      at Object.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:72:11)
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-Vfqxcs/bqplot/setup.py", line 204, in <module>
      setup(**setup_args)
    File "/home/steve98654/anaconda/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/home/steve98654/anaconda/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/home/steve98654/anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/home/steve98654/anaconda/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 176, in run
      self.run_command('build')
    File "/home/steve98654/anaconda/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/home/steve98654/anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/home/steve98654/anaconda/lib/python2.7/distutils/command/build.py", line 127, in run
      self.run_command(cmd_name)
    File "/home/steve98654/anaconda/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/home/steve98654/anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-Vfqxcs/bqplot/setup.py", line 154, in run
      self.run_command('js')
    File "/home/steve98654/anaconda/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/home/steve98654/anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-Vfqxcs/bqplot/setup.py", line 143, in run
      env=os.environ.copy(),
    File "/home/steve98654/anaconda/lib/python2.7/subprocess.py", line 540, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['bower', 'install', '--allow-root', '--config.interactive=false']' returned non-zero exit status 1
  
  ----------------------------------------
  Failed building wheel for bqplot
Failed to build bqplot
Installing collected packages: bqplot
  Running setup.py install for bqplot
    Complete output from command /home/steve98654/anaconda/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-Vfqxcs/bqplot/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-n3L33O-record/install-record.txt --single-version-externally-managed --compile:
    /home/steve98654/anaconda/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'License'
      warnings.warn(msg)
    running install
    running build
    running build_py
    running js
    
    Error: Unknown encoding
        at Buffer.write (buffer.js:382:13)
        at new Buffer (buffer.js:261:26)
        at Object.fs.writeFileSync (fs.js:758:12)
        at Function.writeFileSync [as sync] (/usr/local/lib/node_modules/bower/node_modules/insight/node_modules/configstore/node_modules/write-file-atomic/index.js:37:12)
        at Object.create.all.set (/usr/local/lib/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:55:21)
        at Object.Configstore (/usr/local/lib/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:20:11)
        at new Insight (/usr/local/lib/node_modules/bower/node_modules/insight/lib/index.js:37:34)
        at ensureInsight (/usr/local/lib/node_modules/bower/lib/util/analytics.js:25:19)
        at Object.setup (/usr/local/lib/node_modules/bower/lib/util/analytics.js:41:9)
        at Object.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:72:11)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Vfqxcs/bqplot/setup.py", line 204, in <module>
        setup(**setup_args)
      File "/home/steve98654/anaconda/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/home/steve98654/anaconda/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/home/steve98654/anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/steve98654/anaconda/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/command/install.py", line 61, in run
      File "/home/steve98654/anaconda/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/home/steve98654/anaconda/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/home/steve98654/anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/steve98654/anaconda/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/home/steve98654/anaconda/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/home/steve98654/anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-Vfqxcs/bqplot/setup.py", line 154, in run
        self.run_command('js')
      File "/home/steve98654/anaconda/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/home/steve98654/anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-Vfqxcs/bqplot/setup.py", line 143, in run
        env=os.environ.copy(),
      File "/home/steve98654/anaconda/lib/python2.7/subprocess.py", line 540, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['bower', 'install', '--allow-root', '--config.interactive=false']' returned non-zero exit status 1
    
    ----------------------------------------
Command "/home/steve98654/anaconda/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-Vfqxcs/bqplot/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-n3L33O-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-Vfqxcs/bqplot
steve98654@Riemann:~/LocRepos$ 
```

**Comment by SylvainCorlay** [comment]
@steve98654 thanks for reporting.

Our setup.py runs `bower install` if it can find bower - even though it is a no-op in the case of an installation from pypi. 

Your issue should be solved if you update npm and bower. Although we should keep this one open as a reminder that we should not run bower when installing from pypi.

**Comment by steve98654** [comment]
Thanks Sylvain, I updated node and npm and everything is working fine how.  Do you think it may be worthwhile to put the versions of node/npm/bower that one needs to run your setup.py script in the dependencies section of the github README?

**Comment by SylvainCorlay** [comment]
Yes we definitely need to improve this. Although we will probably just avoid the npm stage when installing from pypi, and require a recent version of node for those willing to run from source.
