### ISSUE TITLE
save_png not working in jupyter

### ISSUE THREAD

**Issue by Medbeij** [bloomberg/bqplot#758]
I'm trying to save a Figure by using 

figure.save_png('filename.png')

and nothing happened! I've checked in the same folder where my notebook existed for 'filename.png' but nothing was there.

**Comment by maartenbreddels** [comment]
Which version is this?

**Comment by maartenbreddels** [comment]
Do you run this from the notebook while you have 1 view open, meaning you see the figure?

**Comment by Medbeij** [comment]
Yes, I've tried to save the png just in the cell below

**Comment by maartenbreddels** [comment]
That should work.
Which browser? And do you see an error msg in the Javascript dev console (i recommend you clear it, and run the save_png again.

**Comment by Medbeij** [comment]
nothing is logged in the console when I run the save_png command,

**Comment by Medbeij** [comment]
Firefox

**Comment by seidlr** [comment]
I have the same issue. The png is never created. But I get an output in the dev console:
```
Exception in Comm callback DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
    at http://localhost:8889/nbextensions/bqplot/index.js?v=20190902193154:1:294930
    at http://localhost:8889/nbextensions/bqplot/index.js?v=20190902193154:1:295371
    at child.get_svg (http://localhost:8889/nbextensions/bqplot/index.js?v=20190902193154:1:295531)
    at child.save_png (http://localhost:8889/nbextensions/bqplot/index.js?v=20190902193154:1:295613)
    at triggerEvents (http://localhost:8889/nbextensions/jupyter-js-widgets/extension.js?v=20190902193154:26514:57)
    at triggerApi (http://localhost:8889/nbextensions/jupyter-js-widgets/extension.js?v=20190902193154:26500:19)
    at eventsApi (http://localhost:8889/nbextensions/jupyter-js-widgets/extension.js?v=20190902193154:26299:16)
    at child.Events.trigger (http://localhost:8889/nbextensions/jupyter-js-widgets/extension.js?v=20190902193154:26490:5)
    at child.handle_custom_messages (http://localhost:8889/nbextensions/bqplot/index.js?v=20190902193154:26:171472)
    at triggerEvents (http://localhost:8889/nbextensions/jupyter-js-widgets/extension.js?v=20190902193154:26514:57) Error: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
    at http://localhost:8889/nbextensions/bqplot/index.js?v=20190902193154:1:294930
    at http://localhost:8889/nbextensions/bqplot/index.js?v=20190902193154:1:295371
    at child.get_svg (http://localhost:8889/nbextensions/bqplot/index.js?v=20190902193154:1:295531)
    at child.save_png (http://localhost:8889/nbextensions/bqplot/index.js?v=20190902193154:1:295613)
    at triggerEvents (http://localhost:8889/nbextensions/jupyter-js-widgets/extension.js?v=20190902193154:26514:57)
    at triggerApi (http://localhost:8889/nbextensions/jupyter-js-widgets/extension.js?v=20190902193154:26500:19)
    at eventsApi (http://localhost:8889/nbextensions/jupyter-js-widgets/extension.js?v=20190902193154:26299:16)
    at child.Events.trigger (http://localhost:8889/nbextensions/jupyter-js-widgets/extension.js?v=20190902193154:26490:5)
    at child.handle_custom_messages (http://localhost:8889/nbextensions/bqplot/index.js?v=20190902193154:26:171472)
    at triggerEvents (http://localhost:8889/nbextensions/jupyter-js-widgets/extension.js?v=20190902193154:26514:57) {header: {…}, msg_id: "e3a75fbc-d8355b65fb6a8219807a2653", msg_type: "comm_msg", parent_header: {…}, metadata: {…}, …}```

bqplot `0.11.7`

**Comment by nvaytet** [comment]
I have the same issue. Neither `save_png` nor `save_svg` appear to work.
It also is not working if I call this from inside a script and run it from the terminal instead of a jupyter notebook.

Ubuntu 18.04, bqplot 0.11.8

**Comment by mrinalraghupathi** [comment]
Same issue here

```
Figure.js:702 Uncaught (in promise) DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
    at get_css (http://localhost:8888/static/lab/vendors~main.7fe919061ddcad719448.js:756707:41)
    at http://localhost:8888/static/lab/vendors~main.7fe919061ddcad719448.js:756762:17
get_css @ Figure.js:702
(anonymous) @ Figure.js:757
Promise.then (async)
save_png @ Figure.js:813
triggerEvents @ backbone.js:370
triggerApi @ backbone.js:356
eventsApi @ backbone.js:155
Events.trigger @ backbone.js:346
handle_custom_messages @ FigureModel.js:42
triggerEvents @ backbone.js:370
triggerApi @ backbone.js:356
eventsApi @ backbone.js:155
Events.trigger @ backbone.js:346
push.rynU.WidgetModel._handle_comm_msg @ widget.js:217
_handleCommMsg @ default.js:1005
_handleMessage @ default.js:1071
async function (async)
_handleMessage @ default.js:1035
(anonymous) @ default.js:122
Promise.then (async)
DefaultKernel._onWSMessage @ default.js:119
serverconnection.js:193 Fetch finished loading: PUT "http://localhost:8888/api/contents/Dropbox/notebooks/BQplot.ipynb?1574639074706".
```

`bpplot 0.12.1`

This was working before I upgraded from `0.11.6`

Using MacOS Sierra 10.12.6 and Chrome Version 78.0.3904.97

**Comment by mrinalraghupathi** [comment]
Doesn't work on `bqplot 0.11.6` now either. Googling the first line of the error seems to indicate this has something to do with CORS in the browser. It fails on Firefox as well:

Error in the console for Firefox

```
DOMException: "The operation is insecure." vendors~main.bfbef50f5f07e95abfc3.js:512849:25
    _msgChain http://localhost:8888/static/lab/vendors~main.bfbef50f5f07e95abfc3.js:512849
```

Firefox version `70.0.1`

**Comment by mrinalraghupathi** [comment]
For what it's worth the suggestion made here to disable jupyterlab-drawio extension fixed the issue:

https://github.com/jupyterlab/jupyterlab/issues/6806

**Comment by maartenbreddels** [comment]
> and nothing happened! I've checked in the same folder where my notebook existed for 'filename.png' but nothing was there.

Note that bqplot should give you a download window with that filename as suggested filename, it will not save it to disk.

The other messages (DOMException/cssRules) seem to be from jupyterlab. My best guess is that there is 1 css file loaded from a server that is not the origin (localhost:8888), which will fail getting the stylestyle (which is forbidden). Could someone check the network tab to see if this is the case. I'll try to reproduce that and see how far I get.

**Comment by mrinalraghupathi** [comment]
Thanks, the CSS files from localhost:8888 appear to be requested by the jupyterlab-drawio extension and disabiling that extension does enable a pop-up window where you can save the image. 

**_Question_**: Is there a plan to make it possible to save the file to a path instead of the popup? 

If you are running on a remote machine and don't have access to the underlying drive, or if you want to include bqplot in an automated process that would be useful.

**Comment by maartenbreddels** [comment]
so it's a missing stylesheet! Well #975 should fix it.

ipyvolume has an option to save it to disk, you could try porting that solution to bqplot.

**Comment by mrinalraghupathi** [comment]
Thanks, I started adding this feature to bqplot by modifying the save_png in Figure.ts and adding a method to figure.py to render to the disk. 

I notice that the image generated (both currently and in the changes I am trying to implement) doesn't have a background color. I can fill the figure with `background_style` but this only fills the plot area and not the area with the axes/title etc...

Is there a way to fill these backgrounds.
